### ISSUE TITLE
The Daemon isn't a Daemon yet

### ISSUE THREAD

**Issue by theodormoroianu** [Unibuc4Ever/Telemetry#3]
What we now call a "Daemon" isn't really a daemon, it's just a regular process.
However, we need to follow some special steps, for instance the ones available with `man daemon`, or [here](http://www.netzmafia.de/skripten/unix/linux-daemon-howto.html).

**Comment by felixp72** [comment]
Closing this issue as we do not have at the moment a clear plan on what to do in this aspect
